name: Run a workout test

on: [push]

jobs:
  run-tests:

      name: Run Psalm tests

      runs-on: ubuntu-latest

      container: 

        image: composer:latest

        volumes:

            - ${{ github.workspace }}:/app

        steps:
          - name: Check out the repo

            uses: actions/checkout@v3

          - name: Running composer install

            run: composer install --no-interaction --no-progress --prefer-dist

          - name: Running psalm

            run: ./vendor/bin/psalm 
