name: Psalm Test

on: push

jobs:
  psalm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Install Psalm
        run: composer require --dev vimeo/psalm

      - name: Set execute permissions for Psalm
        run: chmod +x vendor/bin/psalm
         
      - name: Run Psalm
        run: vendor/bin/psalm --show-info=true --no-cache --diff --shepherd --error-level=1

      - name: Upload Psalm Errors
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: psalm-errors
          path: |
            ./psalm.xml
            ./psalm-errors.json

 