name: Hello github actions

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  run-tests:
    name: Run psalm tests
    runs-on: ubuntu-latest
    container:
      image: composer:latest
      volumes:
        - ${{github.workspace}}:/app
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2

      - name: Running composer install  
         run: composer install  
         
      - name: Running psalm 
         run: ./vendor/bin/psalm  