name: Hello github actions

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  run-tests:
    name: Run psalm tests
    runs-on: ubuntu-latest
    container:
      image: composer:latest
      volumes:
      - ${{github.workspace}}:/app
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2

      - name: Running composer install  
         run: composer install  
      - name: Download psalm
         run: composer require --dev vimeo/psalm
      - name: psalm init
         run: ./vendor/bin/psalm --init   
      - name: Running psalm 
         run: ./vendor/bin/psalm  