name: Run a workout test
on: [push]

jobs:
  run-tests:
      name: Run Psalm tests
      runs-on: ubuntu-latest
      container: 
        image: composer:latest
        volumes:
            - patakias.c/push-ups:/src
        steps:
          - name: Running composer install
            run: composer install
          - name: Running psalm
            run: ./vendor/bin/psalm
